import { Resource } from '@/src/types/resource.type';

export const MOCK_RESOURCES: Resource[] = [
    {
        id: '1',
        title: 'Advanced Calculus Final - 2023',
        category: 'Math',
        type: 'Past Exams',
        format: 'PDF',
        author: {
            id: 'u1',
            name: 'Sarah Jenkins',
            avatar: 'https://picsum.photos/seed/sarah/100/100',
        },
        uploadDate: '2 days ago',
        downloads: '1.2k',
        views: '1.2k',
    },
    {
        id: '2',
        title: 'Quantum Mechanics Notes',
        category: 'Physics',
        type: 'Revision Notes',
        format: 'DOCX',
        author: {
            id: 'u2',
            name: 'Marcus Thorne',
            avatar: 'https://picsum.photos/seed/marcus/100/100',
        },
        uploadDate: 'Oct 12',
        downloads: '842',
        views: '842',
    },
    {
        id: '3',
        title: 'Genetics Practice Set',
        category: 'Biology',
        type: 'Practice Problems',
        format: 'PDF',
        author: {
            id: 'u3',
            name: 'Elena Vance',
            avatar: 'https://picsum.photos/seed/elena/100/100',
        },
        uploadDate: '1 week ago',
        downloads: '521',
        views: '521',
    },
    {
        id: '4',
        title: 'World War II Essay Guide',
        category: 'History',
        type: 'Revision Notes',
        format: 'PDF',
        author: {
            id: 'u4',
            name: 'David Ling',
            avatar: 'https://picsum.photos/seed/david/100/100',
        },
        uploadDate: 'Oct 05',
        downloads: '302',
        views: '302',
    },
    {
        id: '5',
        title: 'Microeconomics 101 Formulas',
        category: 'Economics',
        type: 'Revision Notes',
        format: 'PDF',
        author: {
            id: 'u5',
            name: 'Sofia Rodriguez',
            avatar: 'https://picsum.photos/seed/sofia/100/100',
        },
        uploadDate: '3 days ago',
        downloads: '2.1k',
        views: '2.1k',
    },
];
